build:
    tests:
        when:
            event: [pull_request]
        image: registry.online.ntnu.no/dotkom/onlineweb4-testbase
        commands:
            - cp onlineweb4/settings/example-local.py onlineweb4/settings/local.py
            - tox -e $$TESTENV
        auth_config:
            username: $$REGISTRY_USERNAME
            password: $$REGISTRY_PASSWORD
            email: dotkom@online.ntnu.no
cache:
    mount:
        - .tox
matrix:
    TESTENV:
        - flake8
        - isort
        - tests
deploy:
    ssh:
        when:
            branch: develop
        host: nansen.dotkom
        port: 22
        user: root
        commands:
            - /srv/www/ow4dev/deploy.sh
