---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: registry.online.ntnu.no/dotkom/onlineweb4-testbase
    username: {{docker-registry-username}}
    password: {{docker-registry-password}}
    email: {{docker-registry-email}}

- inputs:
  - name: onlineweb4
  - name: node_modules
    path: onlineweb4/node_modules
  - name: webpack
    path: onlineweb4/bundles

run:
  path: sh
  dir: onlineweb4
  args:
  - -exc
  - |
    whoami
    ls -l
    python webpack_resolve.py
    npm run lint
    npm run build:prod
    py.test --cov=apps